fluent(at(c2,b)).
fluent(at(c1,b)).
fluent(on(c2,ferry)).
fluent(on(c1,ferry)).
fluent(at_ferry(b)).
fluent(at(c2,a)).
fluent(at(c1,a)).
fluent(empty_ferry).
fluent(at_ferry(a)).
fluent(on(c3,ferry)).
fluent(at(c3,b)).
fluent(at(c3,a)).
action(debark(c2,b)).
action(debark(c1,b)).
action(board(c2,b)).
action(board(c2,a)).
action(board(c1,b)).
action(board(c1,a)).
action(move(a,b)).
action(debark(c3,b)).
action(debark(c3,a)).
action(debark(c2,a)).
action(debark(c1,a)).
action(move(b,a)).
action(board(c3,b)).
action(board(c3,a)).
init(at(c1,a)).
init(at(c2,a)).
init(at(c3,a)).
init(at_ferry(a)).
init(empty_ferry).
goal(at(c1,b)).
goal(at(c2,b)).
pre(debark(c1,b),at_ferry(b)).
pre(debark(c2,b),at_ferry(b)).
pre(debark(c3,b),at_ferry(b)).
pre(debark(c3,a),at_ferry(a)).
pre(debark(c2,a),at_ferry(a)).
pre(debark(c1,a),at_ferry(a)).
pre(debark(c1,b),on(c1,ferry)).
pre(debark(c2,b),on(c2,ferry)).
pre(debark(c3,b),on(c3,ferry)).
pre(debark(c3,a),on(c3,ferry)).
pre(debark(c2,a),on(c2,ferry)).
pre(debark(c1,a),on(c1,ferry)).
pre(move(a,b),at_ferry(a)).
pre(move(b,a),at_ferry(b)).
pre(board(c1,a),empty_ferry).
pre(board(c2,a),empty_ferry).
pre(board(c3,a),empty_ferry).
pre(board(c3,b),empty_ferry).
pre(board(c2,b),empty_ferry).
pre(board(c1,b),empty_ferry).
pre(board(c1,a),at_ferry(a)).
pre(board(c2,a),at_ferry(a)).
pre(board(c3,a),at_ferry(a)).
pre(board(c3,b),at_ferry(b)).
pre(board(c2,b),at_ferry(b)).
pre(board(c1,b),at_ferry(b)).
pre(board(c1,a),at(c1,a)).
pre(board(c2,a),at(c2,a)).
pre(board(c3,a),at(c3,a)).
pre(board(c3,b),at(c3,b)).
pre(board(c2,b),at(c2,b)).
pre(board(c1,b),at(c1,b)).
add(move(a,b),at_ferry(b)).
add(board(c3,a),on(c3,ferry)).
add(board(c2,a),on(c2,ferry)).
add(board(c1,a),on(c1,ferry)).
add(move(b,a),at_ferry(a)).
add(debark(c1,a),at(c1,a)).
add(debark(c2,a),at(c2,a)).
add(debark(c3,a),at(c3,a)).
add(debark(c3,b),at(c3,b)).
add(debark(c2,b),at(c2,b)).
add(debark(c1,b),at(c1,b)).
add(debark(c1,a),empty_ferry).
add(debark(c2,a),empty_ferry).
add(debark(c3,a),empty_ferry).
add(debark(c3,b),empty_ferry).
add(debark(c2,b),empty_ferry).
add(debark(c1,b),empty_ferry).
add(board(c1,b),on(c1,ferry)).
add(board(c2,b),on(c2,ferry)).
add(board(c3,b),on(c3,ferry)).
del(debark(c1,b),on(c1,ferry)).
del(debark(c2,b),on(c2,ferry)).
del(debark(c3,b),on(c3,ferry)).
del(debark(c3,a),on(c3,ferry)).
del(debark(c2,a),on(c2,ferry)).
del(debark(c1,a),on(c1,ferry)).
del(move(a,b),at_ferry(a)).
del(move(b,a),at_ferry(b)).
del(board(c1,a),empty_ferry).
del(board(c2,a),empty_ferry).
del(board(c3,a),empty_ferry).
del(board(c3,b),empty_ferry).
del(board(c2,b),empty_ferry).
del(board(c1,b),empty_ferry).
del(board(c1,a),at(c1,a)).
del(board(c2,a),at(c2,a)).
del(board(c3,a),at(c3,a)).
del(board(c3,b),at(c3,b)).
del(board(c2,b),at(c2,b)).
del(board(c1,b),at(c1,b)).
